# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628d9ed20169e91c6a91cd835262bd82c5efbe2109204dfc0617f45687a235a3b29f9a49c6c71d96cca4d157622e75cc9224b455fcd1ac23d7a19316d3e086ce

test:
  secret_key_base: 79da068f5f847bcc2a5af0ef38c6ed5975e976082e8332bfdd40dca3a22a27cead51911b19fe3fff794c029b2f2b7cf5553001ea80f347379736d1b72b62e84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
